#!/usr/bin/env python3
"""Extract waqf-mark outlines from the mushaf fonts into frontend/lib/waqf-glyph-paths.ts.

Waqf marks are combining characters: zero advance, inked far above the
baseline. Browsers disagree on drawing (and measuring) a lone combining mark —
WebKit reports an empty box — so the frontend draws these outlines as SVG
paths instead of shaping text. Re-run after changing either font:

    .venv/bin/python scripts/build_waqf_glyph_paths.py
"""
from __future__ import annotations

import json
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "frontend" / "lib" / "waqf-glyph-paths.ts"

# Stop marks U+06D6–U+06DC, the ayah-end ornament U+06DD (Warsh's رأس آية),
# and the small high marks the Hafs glyph table maps to.
CHARS = [chr(code) for code in range(0x06D6, 0x06DE)] + ["ؕ", "ؗ", "ؔ", "۪", "۫", "۬"]

FONTS = {
    "hafs": ROOT / "static" / "fonts" / "uthmanic_hafs_v20.ttf",
    "warsh": ROOT / "static" / "fonts" / "uthmanic_warsh_v21.ttf",
}


def outlines(path: Path) -> dict[str, dict]:
    font = TTFont(path)
    cmap = font.getBestCmap()
    glyphs = font.getGlyphSet()
    result: dict[str, dict] = {}
    for char in CHARS:
        name = cmap.get(ord(char))
        if not name:
            continue
        pen = SVGPathPen(glyphs)
        glyphs[name].draw(pen)
        bounds = BoundsPen(glyphs)
        glyphs[name].draw(bounds)
        if not bounds.bounds or not pen.getCommands():
            continue
        x_min, y_min, x_max, y_max = bounds.bounds
        # Font units are y-up; the component flips with scale(1,-1).
        result[char] = {"d": pen.getCommands(), "box": [round(x_min), round(y_min), round(x_max), round(y_max)]}
    return result


def main() -> None:
    data = {name: outlines(path) for name, path in FONTS.items()}
    lines = [
        "// Generated by scripts/build_waqf_glyph_paths.py — do not edit by hand.",
        "// Outlines of the waqf marks from Uthmanic Hafs (v20) and Uthmanic Warsh (v21), font units, y-up.",
        "",
        "export type GlyphOutline = {d: string; box: [number, number, number, number]};",
        "",
        f"export const WAQF_GLYPH_PATHS: Record<\"hafs\" | \"warsh\", Record<string, GlyphOutline>> = {json.dumps(data, ensure_ascii=False)};",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    for name, glyphs in data.items():
        print(name, len(glyphs), "glyphs:", " ".join(f"U+{ord(c):04X}" for c in glyphs))


if __name__ == "__main__":
    main()
